export const ActionTypes = {
  SOCKET_CREATED: "SOCKET_CREATED",
  SOCKET_CONNECTED: "SOCKET_CONNECTED",
  SOCKET_DISCONNECTED: "SOCKET_DISCONNECTED",
  ROOM_CONNECTED: "ROOM_CONNECTED",
  ROOM_DISCONNECTED: "ROOM_DISCONNECTED",
};
